import type { Metadata } from "next";
import {
  Birthstone,
  Geist,
  Geist_Mono,
  Inter,
  Joan,
  Open_Sans,
} from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-open-sans",
});

const joan = Joan({
  subsets: ["latin"],
  weight: ["400"], // Or include more weights if needed
  display: "swap",
  variable: "--font-joan",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-inter",
  display: "swap",
});

const birthstone = Birthstone({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-birthstone",
  weight: ["400"], // Birthstone supports only weight 400
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tugra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable}  ${birthstone.variable}  ${inter.variable} ${joan.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
